{% set name = "scikit-build" %}
{% set version = "0.11.1" %}
{% set sha256 = "da40dfd69b2456fad1349a894b90180b43712152b8a85d2a00f4ae2ce8ac9a5c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - cmake
    - ninja
    - pip
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - packaging
    - pip
    - setuptools
    - wheel
  run:
    - python
    - cmake
    - distro
    - ninja
    - packaging
    - setuptools
    - wheel

test:
  source_files:
    - tests/*
  requires:
    - cmake
    - cython
    - git
    - make  # [unix]
    - mock
    - ninja
    - path.py
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-runner
    - requests
    - six
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
  imports:
    - skbuild

about:
  home: http://github.com/scikit-build/scikit-build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Improved build system generator for CPython C extensions.
  doc_url: http://scikit-build.readthedocs.org
  dev_url: http://github.com/scikit-build/scikit-build
